# Generated by Django 4.2.5 on 2023-10-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image_upload', '0004_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tier',
        ),
    ]
