# Generated by Django 4.2.5 on 2023-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_upload', '0005_remove_image_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
