# Generated by Django 4.2.5 on 2023-10-06 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Image_upload', '0006_expiringlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringlink',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Image_upload.image'),
        ),
    ]
